Верстка LaunchScreen
ccodderr/ImageFeed pull request #1
Opened 2024-11-13 18:07 UTC by ccodderr

2024-11-15 12:42 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. По условию задания 2 необходимо выставить минимальную версию iOS в 13.0, поддержку только iPhone и оставить поддержку только портретного режима

2024-11-15 12:42 UTC, Kirchberg commented
Если у тебя есть возможность и желание, попробуй сверстать градиентную подложку для даты - это дополнительное задание со звездочкой в этом спринте.

Попробуй создать кастомный UILabel программно, добавив к нему градиент через CAGradientLayer в коде. Переопредели метод layoutSubviews, чтобы обновлять градиент при изменении размера элемента. Это позволит сделать красивую градиентную подложку для даты на уровне кода.

2024-11-22 11:24 UTC, ccodderr commented
у меня Xcode 16 - он не поддерживает iOS 13, только начиная с 15 версии. Я не могу скачать и установить iOS 13
[https://discussions.apple.com/thread/255243148?sortBy=rank](url)

2024-11-22 16:49 UTC, Kirchberg commented
> у меня Xcode 16 - он не поддерживает iOS 13, только начиная с 15 версии. Я не могу скачать и установить iOS 13 [https://discussions.apple.com/thread/255243148?sortBy=rank](url)

В задании не просят устанавливать симулятор на iOS 13.0, только установить его как минимальный таргет, в Xcode 16.1.

На скриншоте ниже указал, что установил iOS 13.0 и проект сбилдился успешно

<img width="1526" alt="image" src="https://github.com/user-attachments/assets/e15dc1ae-674f-440f-af5a-6c1865e01204">

2025-01-08 07:30 UTC, merged